name: MatchMaker
main: com.dumptruckman.minecraft.matchmaker.MatchMakerPlugin
version: maven-version-number
author: dumptruckman

commands:
  match:
    description: Base command for MatchMaker.
    usage: |
           /<command>
  mmkr:
    description: Base command for MatchMaker.
    usage: |
           /<command>
  mm:
    description: Base command for MatchMaker.
    usage: |
           /<command>
  